var express = require('express');
var router = express.Router();
var GoogleSpreadsheet = require('google-spreadsheet');
var async = require('async');
var Mailchimp = require('mailchimp-api-v3')

var chimpKey = require('./mailchimp-api.json'); 
 
var mailchimp = new Mailchimp(chimpKey.mailchimp_api_key);  //API Key from JSON file for security

var doc = new GoogleSpreadsheet('1EnS4hlkup-CNL8jCn3oWhtHBzMud3pbbUfu_q0kXI9w'); //The actual random string in the URL of the spreadsheet you have created.
//Make sure that the spreadsheet you have created has been shared with the "email address" that is generated by creating the API Service Worker
var sheet;

 async.series([
  function setAuth(step) {
    // see notes below for authentication instructions!
    var creds = require('./signin-waiver.json'); //Private API credentials retrieved from creating the google spreadsheet API from the developer dashboard
        doc.useServiceAccountAuth(creds, step);

  },
  function getInfoAndWorksheets(step) {
    doc.getInfo(function(err, info) {
      console.log('Loaded doc: '+info.title+' by '+info.author.email);
      sheet = info.worksheets[0];
      console.log('sheet 1: '+sheet.title+' '+sheet.rowCount+'x'+sheet.colCount);
      step();
    });
  }
    
    ], function(err){
    if( err ) {
      console.log('Error: '+err);
    }
});

/* GET users listing. */
router.post('/', function(req, res, next) {

          console.log(req.body.signin_first);
          console.log(req.body.signin_last);
          console.log(req.body.signin_email);
          console.log(req.body.signin_phone);



doc.addRow(1, { First_Name: req.body.signin_first, Last_Name: req.body.signin_last, Email: req.body.signin_email, Phone_Number: req.body.signin_phone }, function(err) { //The format is header name(1st row title) then the value
  if(err) {
    console.log(err);
  }
});


mailchimp.post('/lists/215ee85909/members', { //List ID (alpha-numeric string) is found under Settings > List Name and Defaults on the list page on your mailchimp
  email_address : req.body.signin_email,
  merge_fields: { FNAME: req.body.signin_first, LNAME: req.body.signin_last, PHONE: req.body.signin_phone}, //These fields have to be as megre fields
  status : 'subscribed'
})
.then(function(results) {
  console.log(results);
})
.catch(function (err) {
  console.log(err);
})



          res.sendStatus(200);


});

module.exports = router;
